apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoruler
  namespace: autorules
  labels:
    app: autoruler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoruler
  template:
    metadata:
      labels:
        app: autoruler
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      containers:
      - name: autosigner
        image: $REGISTRY/karmab/autosigner:latest
      - name: autolabeller
        image: $REGISTRY/karmab/autolabeller:latest
